name: Sync Repo to GitLab

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: keninkujovic/gitlab-sync@2.0.0
      with:
        gitlab_url: https://gitlab.com/endeavouros-filemirror/endeavouros-i3wm-setup.git
        username: ${{ secrets.GITLAB_USR }}
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
